"use client"

import { Download } from 'lucide-react'
import type { Chat } from '@/lib/chat-types'

function chatToMarkdown(chat: Chat): string {
  const lines: string[] = [
    `# ${chat.title}`,
    `*Exported from AksharAI — ${new Date(chat.createdAt).toLocaleDateString()}*`,
    '',
    '---',
    '',
  ]

  for (const msg of chat.messages) {
    if (msg.role === 'user') {
      lines.push(`## User`)
      lines.push(msg.content)
      lines.push('')
    } else if (msg.role === 'assistant') {
      lines.push(`## AksharAI`)
      lines.push(msg.content)
      if (msg.sources && msg.sources.length > 0) {
        lines.push('')
        lines.push('**Sources:**')
        for (const src of msg.sources) {
          lines.push(`- ${src.book} · ${src.reference}${src.title ? ` — ${src.title}` : ''} (score: ${src.score})`)
        }
      }
      lines.push('')
    }
    lines.push('---')
    lines.push('')
  }

  lines.push('*Generated by AksharAI — Transformer-powered RAG over Swaminarayan Scriptures*')
  return lines.join('\n')
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

interface ChatExportProps {
  chat: Chat | null
}

export function ChatExport({ chat }: ChatExportProps) {
  if (!chat || chat.messages.length === 0) return null

  const handleExportMarkdown = () => {
    const md = chatToMarkdown(chat)
    const safeName = chat.title.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
    downloadFile(md, `aksharai_${safeName}.md`, 'text/markdown')
  }

  return (
    <button
      onClick={handleExportMarkdown}
      className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors px-2 py-1 rounded-lg hover:bg-secondary"
      title="Export chat as Markdown"
    >
      <Download className="w-3.5 h-3.5" />
      <span className="hidden sm:inline">Export</span>
    </button>
  )
}
